### ISSUE TITLE
Error during installation if desktop icon doesn't exist

### ISSUE THREAD

**Issue by ArgonAlex** [ionred/choco_hwmonitor#4]
> ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\Users\Public\Desktop\CPUID HWMonitor.lnk' because it does not exist.
> The install of hwmonitor was NOT successful.
> Error while running 'C:\ProgramData\chocolatey\lib\hwmonitor\tools\chocolateyInstall.ps1'.

**Comment by ionred** [comment]
Resolved in with commit #c68dba1
